version: "3.8"

services:
  client:
    image: 192.168.56.10/data-dash/client:v1.0.2
    ports:
      - "3000:3000"
    environment:
      - HOST=0.0.0.0
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == worker
    networks:
      - data-dash-net

  server:
    image: 192.168.56.10/data-dash/server:v1.0.3
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGODB_URI="<your_mongodb_connection_uri>"
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == worker
    networks:
      - data-dash-net

networks:
  data-dash-net:
    driver: overlay
    attachable: true

